### ISSUE TITLE
make tcc finish with a compilation error

### ISSUE THREAD

**Issue by ryukinix** [graph-learning-ita/airnet-holding-ml#4]
@JorgeLuizFranco 
Eu juro que não entendo porque esse arquivo não compila aqui com `make tcc`, todos os outros compilam, mas esse termina com esse erro:

```tex
(./USPSC-classe/ABNT6023-2018.sty

LaTeX Warning: You have requested package `USPSC-classe/ABNT6023-2018',
               but the package provides `ABNT6023-2018'.

)

LaTeX Warning: \include should only be used after \begin{document} on input lin
e 213.

(./USPSC-TCC-pre-textual-OUTROS.tex)
Writing index file 1_main.idx 
/home/lerax/Desktop/workspace/dsc2024/.venv/bin/pygmentize
(/usr/share/texlive/texmf-dist/tex/latex/chemformula/chemformula.sty
(/usr/share/texlive/texmf-dist/tex/latex/units/nicefrac.sty))

./1_main.tex:266: LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.266 \begin{document}
                   
```

É como se tivesse sendo chamado algum include antes do begin, mas não tem nenhum do que li...

_Originally posted by @ryukinix in https://github.com/graph-learning-ita/airnet-holding-ml/pull/3#discussion_r1814887258_

**Comment by JorgeLuizFranco** [comment]
Bem estranho mesmo, pq eu usando tanto pdflatex quanto latexmk funciona 100%, mas vou procurar o que pode ser.

**Comment by ryukinix** [comment]
Não estava funcionando pq na verdade o documento atual "espera" q continue compilando com erros, ignorando-os. Por esse motivo, uma alteração foi feita em #5 no makefile pra:

```
latexmk -shell-escape -interaction=nonstopmode -f -pdf -file-line-error apresentacao.tex
```

Onde os parâmetros `-interaction=nonstopmode -f ` forçam a execução com erros, uma feature muito comum de ser usada no overleaf, aparentemente... Mas eu nunca tinha usado. 

Por esse motivo, estou fechando essa issue.
